files:
  - source: /projects/*/src/main/resources/assets/*/lang/en_us.json
    dest: /*/*.json
    translation: /%original_path%/%locale_with_underscore%.json
    skip_untranslated_strings: true
    skip_untranslated_files: true
